# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a775eb755630fe1156f5857abdf3fc948e43d241bace82cbcaec6fbd1063c8783c2a111da0d2e8e846fd5a909469ba558baf964bacf468386e5269a39a67f478

test:
  secret_key_base: 34df62219eca3233cf278572ac2b0fbbf650e1c069490a5a0ebde326d7db673f5d5c756f529a1629ccd7e15bd7e44e52d830ea4c941c5e832b697f67dd7c2ced

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
